### ISSUE TITLE
Mobile Style

### ISSUE THREAD

**Issue by mcwinter07** [linda-lai/fed-up#47]
Styles need to added for mobile and tablet views.

![Screen Shot 2020-04-12 at 5 05 55 pm](https://user-images.githubusercontent.com/36558508/79062778-62c7c800-7ce0-11ea-8c91-3ab6115546a2.png)

We can utilise flex-wrap  and min-width to respond to mobile and tablet sizes

![Screen Shot 2020-04-12 at 5 06 01 pm](https://user-images.githubusercontent.com/36558508/79062784-678c7c00-7ce0-11ea-8a60-cfd178b2ee57.png)

If we flip the content with a flex-direction on the  container  class we should be able to resolve this across most of the components.

**Comment by linda-lai** [comment]
https://github.com/linda-lai/fed-up/pull/59
